import type { AttachmentPoint } from '../store/useEditorStore';

export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Point {
  x: number;
  y: number;
}

export function getRectCenter(rect: Rect): Point {
  return {
    x: rect.x + rect.width / 2,
    y: rect.y + rect.height / 2,
  };
}

export function distance(a: Point, b: Point): number {
  return Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
}

/**
 * Compute an orthogonal (horizontal-only and vertical-only) path between
 * the borders of two rectangles.
 *
 * The algorithm:
 * 1. Determine the dominant direction between the two rectangle centers.
 * 2. Exit from the most natural side of the source rectangle (left/right if
 *    horizontal-dominant, top/bottom if vertical-dominant).
 * 3. Enter the most natural side of the target rectangle.
 * 4. Build a path of at most 4 points that only uses axis-aligned segments.
 *
 * @param source  The source rectangle.
 * @param target  The target rectangle.
 * @returns       An array of points forming the orthogonal path.
 */
/**
 * Snap a value to the nearest grid multiple.
 * E.g. snapToGrid(37, 20) => 40, snapToGrid(33, 20) => 40, snapToGrid(18, 20) => 20
 */
export function snapToGrid(value: number, gridSize: number): number {
  return Math.round(value / gridSize) * gridSize;
}

/**
 * Snap a coordinate pair to the nearest grid intersection.
 */
export function snapPosition(
  x: number,
  y: number,
  gridSize: number,
): { x: number; y: number } {
  return {
    x: snapToGrid(x, gridSize),
    y: snapToGrid(y, gridSize),
  };
}

/**
 * Check whether two rectangles overlap geometrically.
 * An optional `margin` expands both rectangles before the check, effectively
 * treating rectangles closer than `margin` pixels as overlapping.
 */
export function rectsOverlap(rectA: Rect, rectB: Rect, margin: number = 5): boolean {
  return (
    rectA.x - margin < rectB.x + rectB.width + margin &&
    rectA.x + rectA.width + margin > rectB.x - margin &&
    rectA.y - margin < rectB.y + rectB.height + margin &&
    rectA.y + rectA.height + margin > rectB.y - margin
  );
}

/**
 * Find the nearest position for `draggedRect` that does not overlap with any
 * of the `otherRects`. Candidates are generated by pushing the dragged
 * rectangle to each side of every overlapping rect. The candidate with the
 * smallest Euclidean distance from the original position is returned.
 *
 * If no non-overlapping candidate exists, the original position is returned.
 */
export function findNearestNonOverlappingPosition(
  draggedRect: Rect,
  otherRects: Rect[],
  margin: number = 5,
): { x: number; y: number } {
  const originalPos = { x: draggedRect.x, y: draggedRect.y };

  // If nothing overlaps, return the original position
  if (!otherRects.some((r) => rectsOverlap(draggedRect, r, margin))) {
    return originalPos;
  }

  // Generate candidate positions by pushing away from each other rect
  const candidates: { x: number; y: number }[] = [];
  for (const other of otherRects) {
    if (!rectsOverlap(draggedRect, other, margin)) continue;

    // Push left
    candidates.push({ x: other.x - draggedRect.width - margin, y: draggedRect.y });
    // Push right
    candidates.push({ x: other.x + other.width + margin, y: draggedRect.y });
    // Push up
    candidates.push({ x: draggedRect.x, y: other.y - draggedRect.height - margin });
    // Push down
    candidates.push({ x: draggedRect.x, y: other.y + other.height + margin });
  }

  // Keep only candidates that resolve all overlaps
  const validCandidates = candidates.filter(
    (c) =>
      !otherRects.some((r) =>
        rectsOverlap(
          { ...draggedRect, x: c.x, y: c.y },
          r,
          margin,
        ),
      ),
  );

  if (validCandidates.length === 0) {
    // No valid candidate — return original (stays overlapping)
    return originalPos;
  }

  // Pick the closest candidate
  const originalPoint: Point = { x: draggedRect.x, y: draggedRect.y };
  return validCandidates.reduce((best, candidate) => {
    const d = distance(originalPoint, candidate);
    const bd = distance(originalPoint, best);
    return d < bd ? candidate : best;
  });
}

/** Get a point on a rectangle's edge from an attachment definition */
export function getEdgePoint(rect: Rect, attachment: AttachmentPoint): Point {
  switch (attachment.side) {
    case 'left':   return { x: rect.x, y: rect.y + rect.height * attachment.ratio };
    case 'right':  return { x: rect.x + rect.width, y: rect.y + rect.height * attachment.ratio };
    case 'top':    return { x: rect.x + rect.width * attachment.ratio, y: rect.y };
    case 'bottom': return { x: rect.x + rect.width * attachment.ratio, y: rect.y + rect.height };
  }
}

export function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

/**
 * Given a point near a rectangle, determine the nearest edge attachment point.
 * Finds the closest edge and returns the attachment on that edge.
 */
export function pointToAttachment(rect: Rect, px: number, py: number): AttachmentPoint {
  const left: Point =   { x: rect.x, y: clamp(py, rect.y, rect.y + rect.height) };
  const right: Point =  { x: rect.x + rect.width, y: clamp(py, rect.y, rect.y + rect.height) };
  const top: Point =    { x: clamp(px, rect.x, rect.x + rect.width), y: rect.y };
  const bottom: Point = { x: clamp(px, rect.x, rect.x + rect.width), y: rect.y + rect.height };

  const dLeft = distance({ x: px, y: py }, left);
  const dRight = distance({ x: px, y: py }, right);
  const dTop = distance({ x: px, y: py }, top);
  const dBottom = distance({ x: px, y: py }, bottom);

  const min = Math.min(dLeft, dRight, dTop, dBottom);

  if (min === dLeft)   return { side: 'left',   ratio: clamp((py - rect.y) / rect.height, 0, 1) };
  if (min === dRight)  return { side: 'right',  ratio: clamp((py - rect.y) / rect.height, 0, 1) };
  if (min === dTop)    return { side: 'top',    ratio: clamp((px - rect.x) / rect.width, 0, 1) };
  return                       { side: 'bottom', ratio: clamp((px - rect.x) / rect.width, 0, 1) };
}

/**
 * Given two edge points (not centers), compute an orthogonal path between them.
 */
export function computeOrthogonalPathBetweenPoints(
  exit: Point,
  entry: Point,
): Point[] {
  const dx = entry.x - exit.x;
  const dy = entry.y - exit.y;
  const isHorizontal = Math.abs(dx) >= Math.abs(dy);

  const midX = (exit.x + entry.x) / 2;
  const midY = (exit.y + entry.y) / 2;

  if (isHorizontal) {
    if (Math.abs(exit.y - entry.y) < 1) {
      return [exit, entry];
    }
    return [
      exit,
      { x: midX, y: exit.y },
      { x: midX, y: entry.y },
      entry,
    ];
  } else {
    if (Math.abs(exit.x - entry.x) < 1) {
      return [exit, entry];
    }
    return [
      exit,
      { x: exit.x, y: midY },
      { x: entry.x, y: midY },
      entry,
    ];
  }
}

export function computeOrthogonalPath(
  source: Rect,
  target: Rect,
  sourceAttachment?: AttachmentPoint,
  targetAttachment?: AttachmentPoint,
): Point[] {
  // If attachments are provided, use fixed edge points
  if (sourceAttachment && targetAttachment) {
    const exit = getEdgePoint(source, sourceAttachment);
    const entry = getEdgePoint(target, targetAttachment);
    return computeOrthogonalPathBetweenPoints(exit, entry);
  }

  const sourceCenter = getRectCenter(source);
  const targetCenter = getRectCenter(target);

  const dx = targetCenter.x - sourceCenter.x;
  const dy = targetCenter.y - sourceCenter.y;

  const isHorizontal = Math.abs(dx) >= Math.abs(dy);

  let exit: Point;
  let entry: Point;

  // ── Non-overlapping: original logic unchanged ──
  if (!rectsOverlap(source, target, 0)) {
    if (isHorizontal) {
      // Horizontal routing: exit from left/right, enter from right/left
      if (dx >= 0) {
        // Target is to the right (or directly below with tie)
        exit = { x: source.x + source.width, y: source.y + source.height / 2 };
        entry = { x: target.x, y: target.y + target.height / 2 };
      } else {
        // Target is to the left
        exit = { x: source.x, y: source.y + source.height / 2 };
        entry = { x: target.x + target.width, y: target.y + target.height / 2 };
      }

      const midX = (exit.x + entry.x) / 2;

      if (Math.abs(exit.y - entry.y) < 1) {
        // Aligned horizontally – straight line
        return [exit, entry];
      }

      return [
        exit,
        { x: midX, y: exit.y },
        { x: midX, y: entry.y },
        entry,
      ];
    } else {
      // Vertical routing: exit from top/bottom, enter from bottom/top
      if (dy >= 0) {
        // Target is below (or directly to the right with tie)
        exit = { x: source.x + source.width / 2, y: source.y + source.height };
        entry = { x: target.x + target.width / 2, y: target.y };
      } else {
        // Target is above
        exit = { x: source.x + source.width / 2, y: source.y };
        entry = { x: target.x + target.width / 2, y: target.y + target.height };
      }

      const midY = (exit.y + entry.y) / 2;

      if (Math.abs(exit.x - entry.x) < 1) {
        // Aligned vertically – straight line
        return [exit, entry];
      }

      return [
        exit,
        { x: exit.x, y: midY },
        { x: entry.x, y: midY },
        entry,
      ];
    }
  }

  // ── Overlapping: degenerate fallback ──
  // Route via the outward-facing sides so the path clears both rectangles.
  if (isHorizontal) {
    if (dx >= 0) {
      // Target is to the right → exit from LEFT of source, enter from RIGHT of target
      exit = { x: source.x, y: source.y + source.height / 2 };
      entry = { x: target.x + target.width, y: target.y + target.height / 2 };
    } else {
      // Target is to the left → exit from RIGHT of source, enter from LEFT of target
      exit = { x: source.x + source.width, y: source.y + source.height / 2 };
      entry = { x: target.x, y: target.y + target.height / 2 };
    }

    // Go outward horizontally, then vertically, then horizontally back to entry
    const outwardDir = exit.x < sourceCenter.x ? -1 : 1;
    const outwardDist = Math.max(source.width, target.width, 60);
    const outwardX = exit.x + outwardDir * outwardDist;

    return [
      exit,
      { x: outwardX, y: exit.y },
      { x: outwardX, y: entry.y },
      entry,
    ];
  } else {
    if (dy >= 0) {
      // Target is below → exit from TOP of source, enter from BOTTOM of target
      exit = { x: source.x + source.width / 2, y: source.y };
      entry = { x: target.x + target.width / 2, y: target.y + target.height };
    } else {
      // Target is above → exit from BOTTOM of source, enter from TOP of target
      exit = { x: source.x + source.width / 2, y: source.y + source.height };
      entry = { x: target.x + target.width / 2, y: target.y };
    }

    // Go outward vertically, then horizontally, then vertically back to entry
    const outwardDir = exit.y < sourceCenter.y ? -1 : 1;
    const outwardDist = Math.max(source.height, target.height, 60);
    const outwardY = exit.y + outwardDir * outwardDist;

    return [
      exit,
      { x: exit.x, y: outwardY },
      { x: entry.x, y: outwardY },
      entry,
    ];
  }
}

/**
 * Compute an orthogonal path that passes through user-defined waypoints.
 *
 * When no waypoints are provided, delegates to `computeOrthogonalPath` for the
 * standard exit-to-entry routing.
 *
 * When waypoints exist, the path is constructed as a chain of orthogonal segments:
 *   start -> waypoint[0] -> waypoint[1] -> ... -> waypoint[n-1] -> end
 * where each pair is routed via `computeOrthogonalPathBetweenPoints`.
 *
 * @param source             The source rectangle.
 * @param target             The target rectangle.
 * @param sourceAttachment   Fixed exit point on the source (optional).
 * @param targetAttachment   Fixed entry point on the target (optional).
 * @param waypoints          User-placed control points the path should pass through.
 * @returns                  An array of points forming the full orthogonal path.
 */
export function computePathWithWaypoints(
  sourceRect: Rect,
  targetRect: Rect,
  sourceAttachment?: AttachmentPoint,
  targetAttachment?: AttachmentPoint,
  waypoints?: Point[],
): Point[] {
  if (!waypoints || waypoints.length === 0) {
    return computeOrthogonalPath(sourceRect, targetRect, sourceAttachment, targetAttachment);
  }

  // Get start and end edge points
  const start = sourceAttachment
    ? getEdgePoint(sourceRect, sourceAttachment)
    : getRectCenter(sourceRect);
  const end = targetAttachment
    ? getEdgePoint(targetRect, targetAttachment)
    : getRectCenter(targetRect);

  // Build path: start -> waypoints -> end
  // Each segment routes orthogonally between consecutive points
  const allPoints = [start, ...waypoints, end];
  const result: Point[] = [allPoints[0]];

  for (let i = 0; i < allPoints.length - 1; i++) {
    const segment = computeOrthogonalPathBetweenPoints(allPoints[i], allPoints[i + 1]);
    // Skip the first point of each segment (it overlaps the last point of the previous segment)
    for (let j = 1; j < segment.length; j++) {
      result.push(segment[j]);
    }
  }

  return result;
}
